import { Caveat } from "next/font/google";
import { Architects_Daughter } from "next/font/google";
import "./globals.css";

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

const archictects_dauughter = Architects_Daughter({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  variable: "--font-architects-daughter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={archictects_dauughter.className}>{children}</body>
    </html>
  );
}
